name: Notificar Discord Automático
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Essencial para salvar o manga_cache.json de volta no GitHub
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Rodar Script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node notificar.js

      - name: Salvar Alterações no Cache
        run: |
          git config --global user.name "Mangatachi Bot"
          git config --global user.email "bot@mangatachi.com"
          # Adiciona o arquivo mesmo que ele tenha acabado de ser criado
          git add manga_cache.json
          # O [skip ci] evita que o commit do bot dispare o script novamente em loop
          git commit -m "chore: update manga cache [skip ci]" || echo "Nada para atualizar"
          git pull --rebase origin main
          git push origin main
